---
- name: Install GitLab
  hosts: gitlab
  remote_user: root

  tasks:
    - name: Ensure /opt/gitlab exists
      file:
        path: /opt/gitlab
        state: directory
        mode: "0755"

    - name: Copy Docker Compose file
      copy:
        src: gitlab.docker-compose.yml
        dest: /opt/gitlab/docker-compose.yml

    - name: Start Docker Compose
      shell: docker-compose -f /opt/gitlab/docker-compose.yml up -d

    - name: Wait for URL to respond with status 200
      uri:
        url: https://127.0.0.1/users/sign_in
        method: GET
        status_code: 200
        validate_certs: no
      register: response
      until: response.status == 200
      retries: 200
      delay: 5
      tags:
        - liveliness-check
